# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sls-cognito-backend

frameworkVersion: '3'

provider:
  name: aws
  profile: serverlessUser
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

  # environment variables
  environment:
    REGION: ${self:provider.region}

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
          path: hello
          method: GET
